name: Release

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  release:
    name: Release on ${{ matrix.target }}
    runs-on: ${{ matrix.target }}
    strategy:
      fail-fast: false
      matrix:
        target: [macos-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@master
      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1.3.1
        with:
          toolchain: stable
      - name: Instal OpenSSL on Linux
        if: runner.os == 'Linux'
        run: sudo apt install libssl-dev
      - name: Compile
        run: cargo build -r
        env:
          OPENSSL_STATIC: 1
      - name: Generate artifacts for Linux & Mac
        uses: vimtor/action-zip@v1
        with:
          files: target/release/katan-cli README.md LICENSE
          dest: katan-cli.zip
        if: runner.os != 'Windows'
      - name: Upload artifacts
        uses: WebFreak001/upload-asset@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: ./katan-cli.zip
          mime: application/zip
          name: katan-cli-x86_64-${{ runner.os.lowercase }}.zip
